### PR TITLE
Fix missing header

### PR DESCRIPTION
**Pull request by bws**
Compile failed due to missing <iostream>

### CODE REVIEW

**Comment by bws** [comment]
If it's okay for my (Brad S) to merge this I will, but I have no idea what the rules are here.

**Comment by cadejager** [comment]
I see nothing wrong with this pull and if we want to integrate it I think sooner is better than later.

However, I am unsure how to reproduce a warning/error. Brad, could you please provide your environment information and configure flags?

There are compile warnings that I need to clean up but I don't think that this is related to the ones I am seeing.

**Comment by brettkettering** [comment]
Brad:

I think that you can merge this pull request. Core Developers have write access. If it doesn't work, let me know. Please coordinate with Chris DeJager to ensure on the compile warnings and reproducing any warning/error messages.

**Comment by bws** [comment]
It was the following config line

./configure --prefix=/users/bws/sw/toss-x86_64/pftool

**Pull request merged**
